python:
    #- 3.7
    - 3.6
      #- 2.7

pin_run_as_build:
  python: x.x.x

numpy:
    - 1.14

VTK_WITH_OSMESA:
    - False
    - True
CONDA_BUILD_SYSROOT:
    - /opt/MacOSX10.9.sdk        # [osx]
    # - /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk



